In [5]:
from mtm026 import *
S = np.array([
    [180, 0, 0],
    [0, 120, 90],
    [0, 90, 75]
])

huvudspänningar, riktningar = eig(S)
display(huvudspänningar, riktningar)

array([  4.73012342+0.j, 190.26987658+0.j, 180.        +0.j])

array([[ 0.        ,  0.        ,  1.        ],
       [ 0.61541221, -0.78820544,  0.        ],
       [-0.78820544, -0.61541221,  0.        ]])

In [6]:
#b)
n = 1/np.sqrt(3)*np.array([[1], [1], [1]])

s = S@n
sigma = n.T @ s
tau = np.sqrt(s.T @ s - sigma**2)
display(sigma)
display(tau)

array([[185.]])

array([[18.70828693]])