In [4]:
from mtm026 import *
S = np.array([
    [20, 30, 0],
    [30, 60, 40],
    [0, 40, 20]
])

huvudspänningar, riktningar = eig(S)
display(huvudspänningar, riktningar)

array([ 93.85164807+0.j,  20.        +0.j, -13.85164807+0.j])

array([[-3.36377286e-01,  8.00000000e-01,  4.96840338e-01],
       [-8.28067230e-01,  9.54223708e-17, -5.60628809e-01],
       [-4.48503047e-01, -6.00000000e-01,  6.62453784e-01]])

In [5]:
n = np.array([[-4], [0], [3]])/5
s = S @ n
sigma = n.T @s
tau = np.sqrt(s.T @ s - sigma**2)
display(sigma, tau)

array([[20.]])

array([[0.]])