In [3]:
from mtm026 import *
E = 1
I = 1
P = 1
L = 1
EI = E*I
K = np.zeros([6, 6])
k_sig = np.zeros([6, 6])

ke1 = Ke_balk(EI=EI, L = L)
ke2 = Ke_balk(EI = 2*EI, L = L)
ke_sig = Ke_sigma_balk(P, L)

assem(K, ke1, dofs=[1, 2, 3, 4])
assem(K, ke2, dofs=[3, 4, 5, 6])
assem(k_sig, ke_sig, dofs = [3, 4, 5, 6])
free_dofs=[4, 5]
K_red = extract_block(K, free_dofs, free_dofs)
k_red_sig = extract_block(k_sig, free_dofs, free_dofs)

display(K_red)
display(k_red_sig)
display(free_dofs)

pk, moder = eig(K_red, k_red_sig)

display(pk)
display(moder)
display(np.real(np.min(pk)))

array([[ 12., -12.],
       [-12.,  24.]])

array([[ 0.13333333, -0.1       ],
       [-0.1       ,  1.2       ]])

[4, 5]

array([90.75545701+0.j, 10.57787632+0.j])

array([[-0.99940736,  0.71858971],
       [ 0.0344228 ,  0.69543427]])

10.577876324338915