In [10]:
from mtm026 import *

K = np.zeros([10, 10])
K_sigma = np.zeros([10, 10])
E=1
I = 1
L = 1
P = 1
ke1 = Ke_balk(EI = E*I, L = L)
ke2 = Ke_balk(EI = E*I/10, L = L/8)
Ke_sigma = Ke_sigma_balk(P=P, L=L)
assem(K, ke2, dofs= [1, 2, 3, 4])
assem(K, ke1, dofs= [5, 4, 6, 7])
assem(K, ke2, dofs= [8, 7, 9, 10])
assem(K_sigma, Ke_sigma, dofs=[5, 4, 6, 7])

free_dofs = [4, 7]
K_red = extract_block(K, free_dofs, free_dofs)
K_red_sigma = extract_block(K_sigma, free_dofs, free_dofs)

display(K_red)
display(K_red_sigma)
display(free_dofs)

egenvärden, egenvektorer = eigh(K_red, K_red_sigma)
Pk = np.round(np.real(np.min(egenvärden)), 3)
display(Pk)

E = 200e9
I = 5e-6
A = 8e-3
alpha = 1e-5
L = 6

pkr = Pk*E*I/L**2
display(pkr)
print(egenvärden)
print(egenvektorer)



array([[7.2, 2. ],
       [2. , 7.2]])

array([[ 0.13333333, -0.03333333],
       [-0.03333333,  0.13333333]])

[4, 7]

31.2

866666.6666666667

[31.2 92. ]
[[-1.73205081  2.23606798]
 [ 1.73205081  2.23606798]]
