In [22]:
from mtm026 import *

K = np.zeros([8, 8])
k_sig = np.zeros([8, 8])
E = 1
P = 1
I = 1
L = 1

In [23]:
ke = Ke_balk(EI = E*I, L=L)
ke_sig1 = Ke_sigma_balk(P=P, L=L)
assem(K, ke, dofs=[1, 2, 3, 4])
assem(K, ke, dofs=[3, 4, 5, 6])
assem(K, ke, dofs=[5, 6, 7, 8])
assem(k_sig, ke_sig1, dofs=[3, 4, 5, 6])


array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.2       ,  0.1       , -1.2       ,
         0.1       ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.1       ,  0.13333333, -0.1       ,
        -0.03333333,  0.        ,  0.        ],
       [ 0.        ,  0.        , -1.2       , -0.1       ,  1.2       ,
        -0.1       ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.1       , -0.03333333, -0.1       ,
         0.13333333,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ]])

In [24]:
free_dofs = [2, 4, 6, 8]
K_red = extract_block(K, free_dofs, free_dofs)
k_red_sigma = extract_block(k_sig, free_dofs, free_dofs)
display(K_red)
display(k_red_sigma)

array([[4., 2., 0., 0.],
       [2., 8., 2., 0.],
       [0., 2., 8., 2.],
       [0., 0., 2., 4.]])

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.13333333, -0.03333333,  0.        ],
       [ 0.        , -0.03333333,  0.13333333,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [25]:
egenvärden, egenvektorer = eig(K_red, k_red_sigma)
pk = np.round(np.real(np.min(egenvärden)), 3)
display(pk)
display(egenvärden)
display(egenvektorer)

30.0

array([inf+0.j, 90.+0.j, 30.+0.j, inf+0.j])

array([[ 1.00000000e+00, -3.16227766e-01, -3.16227766e-01,
         0.00000000e+00],
       [ 0.00000000e+00,  6.32455532e-01,  6.32455532e-01,
         1.24126708e-17],
       [ 0.00000000e+00,  6.32455532e-01, -6.32455532e-01,
        -4.96506831e-17],
       [ 0.00000000e+00, -3.16227766e-01,  3.16227766e-01,
         1.00000000e+00]])