In [21]:
from mtm026 import *
K = np.zeros([7, 7])
K_sig = np.zeros([7, 7])
E=1
I = 1
L = 1
P = 1
k = E*I/L**3

In [22]:
ke = Ke_balk(EI=E*I, L=L)
ke_sig = Ke_sigma_balk(P=P, L=L)
ke_fjäder = Ke_fjäder(k)
assem(K, ke, dofs=[1, 2, 3, 4])
assem(K, ke, dofs=[3, 4, 5, 6])
assem(K, ke_fjäder, dofs=[7, 3])
assem(K_sig, ke_sig, dofs=[3, 4, 5, 6])
assem(K_sig, ke_sig, dofs=[1, 2, 3, 4])
display(K)
display(K_sig)

array([[ 12.,   6., -12.,   6.,   0.,   0.,   0.],
       [  6.,   4.,  -6.,   2.,   0.,   0.,   0.],
       [-12.,  -6.,  25.,   0., -12.,   6.,  -1.],
       [  6.,   2.,   0.,   8.,  -6.,   2.,   0.],
       [  0.,   0., -12.,  -6.,  12.,  -6.,   0.],
       [  0.,   0.,   6.,   2.,  -6.,   4.,   0.],
       [  0.,   0.,  -1.,   0.,   0.,   0.,   1.]])

array([[ 1.2       ,  0.1       , -1.2       ,  0.1       ,  0.        ,
         0.        ,  0.        ],
       [ 0.1       ,  0.13333333, -0.1       , -0.03333333,  0.        ,
         0.        ,  0.        ],
       [-1.2       , -0.1       ,  2.4       ,  0.        , -1.2       ,
         0.1       ,  0.        ],
       [ 0.1       , -0.03333333,  0.        ,  0.26666667, -0.1       ,
        -0.03333333,  0.        ],
       [ 0.        ,  0.        , -1.2       , -0.1       ,  1.2       ,
        -0.1       ,  0.        ],
       [ 0.        ,  0.        ,  0.1       , -0.03333333, -0.1       ,
         0.13333333,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ]])

In [23]:
free_dofs = [3, 4, 6]
K_red = extract_block(K, free_dofs, free_dofs)
K_red_sigma= extract_block(K_sig, free_dofs, free_dofs)
display(K_red)
display(K_red_sigma)

egenvärden, egenvektorer = eigh(K_red, K_red_sigma)
display(np.round(np.min(egenvärden), 3))
display(egenvärden)
display((egenvektorer))

array([[25.,  0.,  6.],
       [ 0.,  8.,  2.],
       [ 6.,  2.,  4.]])

array([[ 2.4       ,  0.        ,  0.1       ],
       [ 0.        ,  0.26666667, -0.03333333],
       [ 0.1       , -0.03333333,  0.13333333]])

5.533

array([ 5.53268861, 18.84985993, 49.38134035])

array([[ 0.59455474,  0.27654721, -0.02412169],
       [ 0.42837351, -1.20235267, -1.49861409],
       [-1.27950166,  1.36019526, -2.12432209]])