In [9]:
from mtm026 import *

S = np.array([
    [-120, 80, 0],
    [80, 100, 40],
    [0, 40, -120]
])

huvudspänningar, riktningar = eigh(S)
display(np.round(huvudspänningar, 3))


vonmises = np.sqrt((huvudspänningar[0]-huvudspänningar[1])**2 + (huvudspänningar[1] - huvudspänningar[2])**2 + (huvudspänningar[2] - huvudspänningar[0])**2)/np.sqrt(2)
display(vonmises)
n = np.array([1, 1, 1])*(1/np.sqrt(3))
m = np.array([1, -1, 0])*(1/np.sqrt(2))
display(n)
s = np.dot(S, n)
display(s)
sigma = np.dot(s, n)
display(sigma)
tau= np.dot(s, m)
display(tau)

array([-151.774, -120.   ,  131.774])

269.07248094147434

array([0.57735027, 0.57735027, 0.57735027])

array([-23.09401077, 127.01705922, -46.18802154])

33.333333333333336

-106.14455552060438